export const LOGIN_INIT = '[LOGIN] LOGIN_INIT';
export const LOGIN_SUCCESS = '[LOGIN] LOGIN_SUCCESS';
export const LOGIN_ERROR = '[LOGIN] LOGIN_ERROR';
export const LOGOUT_INIT = '[LOGIN] LOGOUT_INIT';
export const USER_FORM_FIELD_CHANGE = '[LOGIN] USER_FORM_FIELD_CHANGE';
