export const LOGIN_INIT = '[LOGIN] LOGIN_INIT';
export const LOGIN_SUCCESS = '[LOGIN] LOGIN_SUCCESS';
export const LOGIN_ERROR = '[LOGIN] LOGIN_ERROR';
export const LOGOUT_INIT = '[LOGIN] LOGOUT_INIT';
export const USER_FORM_FIELD_CHANGE = '[LOGIN] USER_FORM_FIELD_CHANGE';
export const USER_CREATE_INIT = '[LOGIN] USER_CREATE_INIT';
export const USER_CREATE_SUCCESS = '[LOGIN] USER_CREATE_SUCCESS';
export const USER_CREATE_ERROR = '[LOGIN] USER_CREATE_ERROR';
