export const SUBSCRIPTION_CREATE_INIT = '[SUBSCRIPTIONS] SUBSCRIPTION_CREATE_INIT';
export const SUBSCRIPTION_CREATE_SUCCESS = '[SUBSCRIPTIONS] SUBSCRIPTION_CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_ERROR = '[SUBSCRIPTIONS] SUBSCRIPTION_CREATE_ERROR';
