export const SUBSCRIPTION_CREATE_INIT = '[SUBSCRIPTIONS] SUBSCRIPTION_CREATE_INIT';
export const SUBSCRIPTION_CREATE_SUCCESS = '[SUBSCRIPTIONS] SUBSCRIPTION_CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_ERROR = '[SUBSCRIPTIONS] SUBSCRIPTION_CREATE_ERROR';
export const SUBSCRIPTIONS_LIST_INIT = '[SUBSCRIPTIONS] SUBSCRIPTIONS_LIST_INIT';
export const SUBSCRIPTIONS_LIST_SUCCESS = '[SUBSCRIPTIONS] SUBSCRIPTIONS_LIST_SUCCESS';
export const SUBSCRIPTIONS_LIST_ERROR = '[SUBSCRIPTIONS] SUBSCRIPTIONS_LIST_ERROR';
