export const REVIEWS_LIST_INIT = '[REVIEWS] REVIEWS_LIST_INIT';
export const REVIEWS_LIST_SUCCESS = '[REVIEWS] REVIEWS_LIST_SUCCESS';
export const REVIEWS_LIST_ERROR = '[REVIEWS] REVIEWS_LIST_ERROR';
export const REVIEWS_CREATE_INIT = '[REVIEWS] REVIEWS_CREATE_INIT';
export const REVIEWS_CREATE_SUCCESS = '[REVIEWS] REVIEWS_CREATE_SUCCESS';
export const REVIEWS_CREATE_ERROR = '[REVIEWS] REVIEWS_CREATE_ERROR';
