export const NOTIFICATIONS_LIST_INIT = '[NOTIFICATIONS] NOTIFICATIONS_LIST_INIT';
export const NOTIFICATIONS_LIST_SUCCESS = '[NOTIFICATIONS] NOTIFICATIONS_LIST_SUCCESS';
export const NOTIFICATIONS_LIST_ERROR = '[NOTIFICATIONS] NOTIFICATIONS_LIST_ERROR';
